import string

## NOMINALS
NOMINAL_TYPE_INTEGER = "INTEGER"
NOMINAL_TYPE_FLOAT = "FLOAT"
NOMINAL_TYPE_PLUS = "PLUS"
NOMINAL_TYPE_MINUS = "MINUS"
NOMINAL_TYPE_MULTIPLY = "MULTIPLY"
NOMINAL_TYPE_DIVIDE = "DIVIDE"
NOMINAL_TYPE_POWER = "POWER"
NOMINAL_TYPE_LEFT_PARENTESIS = "LPARENTESIS"
NOMINAL_TYPE_RIGHT_PARENTESIS = "RPARENTESIS"
NOMINAL_TYPE_EOF = "ENDOFFILE"
NOMINAL_TYPE_IDENTIFIER = "IDENTIFIER"
NOMINAL_TYPE_KEYWORD = "KEYWORD"
NOMINAL_TYPE_EQUALS = "EQUALS"
NOMINAL_TYPE_PRINT = "<PRINT>"

## IGNORE CHARS
IGNORED_CHARS = [" ", " \t"]

## DIGITS
DIGITS = "0123456789"

## LETTERS
LETTERS = string.ascii_letters

## ACCEPTED_CHARS
ACCEPTED_CHARS = LETTERS + DIGITS + "_"

## KEYWORDS
VARIABLE = "$"
PRINT = "print"

## KEYWORDS LIST
KEYWORDS_LIST = [VARIABLE, PRINT]
