## TOKENS
TOKEN_TYPE_INTEGER = "INTEGER"
TOKEN_TYPE_FLOAT = "FLOAT"
TOKEN_TYPE_PLUS = "PLUS"
TOKEN_TYPE_MINUS = "MINUS"
TOKEN_TYPE_MULTIPLY = "MULTIPLY"
TOKEN_TYPE_DIVIDE = "DIVIDE"
TOKEN_TYPE_POWER = "POWER"
TOKEN_TYPE_LEFT_PARENTESIS = "LPARENTESIS"
TOKEN_TYPE_RIGHT_PARENTESIS = "RPARENTESIS"
TOKEN_TYPE_EOF = "ENDOFFILE"


## IGNORE CHARS
IGNORED_CHARS = [" ", " \t"]

## DIGITS
DIGITS = "0123456789"
